<?php

namespace AppBundle\Repository;

/**
 * StepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepsRepository extends \Doctrine\ORM\EntityRepository
{
}
